import { test, expect } from '@playwright/test';
test('browse, save bag, sign in, check out and view an order', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', {name:'Good style. No wahala.'})).toBeVisible();
  await expect(page.getByRole('button', {name:'Add to bag'})).toHaveCount(3);
  for (const image of await page.locator('.product-image img').all()) await image.scrollIntoViewIfNeeded();
  await page.evaluate(() => window.scrollTo(0, 0));
  await expect.poll(() => page.locator('.product-image img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('storefront.png'),fullPage:true});
  await page.getByLabel('Size for The Lagos Essential').selectOption('L');
  await page.getByRole('button', {name:'Add to bag'}).first().click();
  await expect(page.getByText('L added to your bag.')).toBeVisible();
  await page.getByRole('link', {name:'View bag',exact:true}).click();
  await expect(page.getByRole('heading', {name:'Your bag.'})).toBeVisible();
  await page.getByLabel('Quantity for The Lagos Essential, L').selectOption('2');
  await expect(page.getByLabel('Quantity for The Lagos Essential, L')).toBeEnabled();
  await page.reload();
  await expect(page.getByLabel('Quantity for The Lagos Essential, L')).toHaveValue('2');
  await page.getByRole('link', {name:'Continue to checkout'}).click();
  await page.getByRole('link', {name:'Sign in to checkout'}).click();
  await page.getByLabel('Password', {exact:true}).fill('DemoShop2026!');
  await page.getByRole('button', {name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading', {name:'Delivery details'})).toBeVisible();
  await page.getByLabel('Full name').fill('Demo Customer');
  await page.getByLabel('Phone number').fill('08012345678');
  await page.getByLabel('Street address').fill('12 Test Street');
  await page.getByLabel('City', {exact:true}).fill('Lagos');
  await page.getByLabel('State', {exact:true}).fill('Lagos');
  await page.screenshot({path:testInfo.outputPath('checkout.png'),fullPage:true});
  await page.getByRole('button', {name:'Place demo order'}).click();
  await expect(page.getByRole('heading', {name:'Thank you. You’re all set.'})).toBeVisible();
  await page.getByRole('link', {name:'View order history'}).click();
  await expect(page.getByRole('heading', {name:'Order history'})).toBeVisible();
  await expect(page.locator('.order-card').first()).toContainText('Demo Customer');
  await page.getByRole('button', {name:'Sign out'}).click();
  await expect(page.getByRole('heading', {name:'Welcome back'})).toBeVisible();
  expect(errors).toEqual([]);
});
